name: google_signin
description: A Flutter project to demonstrate google login.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_sign_in: ^4.1.1
  font_awesome_flutter: ^8.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/menu.png

  uses-material-design: true